package com.training.poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LeaveApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int leaveId;
	private java.lang.String leaveType;
	private int noOfYearsInCompany;
	private int totNoOfLeaveApplied;
	private int employeeId;
	private int leaveBalance;
	private java.lang.String leaveApplicationStatus;

	public LeaveApplication() {
	}

	public int getLeaveId() {
		return this.leaveId;
	}

	public void setLeaveId(int leaveId) {
		this.leaveId = leaveId;
	}

	public java.lang.String getLeaveType() {
		return this.leaveType;
	}

	public void setLeaveType(java.lang.String leaveType) {
		this.leaveType = leaveType;
	}

	public int getNoOfYearsInCompany() {
		return this.noOfYearsInCompany;
	}

	public void setNoOfYearsInCompany(int noOfYearsInCompany) {
		this.noOfYearsInCompany = noOfYearsInCompany;
	}

	public int getTotNoOfLeaveApplied() {
		return this.totNoOfLeaveApplied;
	}

	public void setTotNoOfLeaveApplied(int totNoOfLeaveApplied) {
		this.totNoOfLeaveApplied = totNoOfLeaveApplied;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public int getLeaveBalance() {
		return this.leaveBalance;
	}

	public void setLeaveBalance(int leaveBalance) {
		this.leaveBalance = leaveBalance;
	}

	public java.lang.String getLeaveApplicationStatus() {
		return this.leaveApplicationStatus;
	}

	public void setLeaveApplicationStatus(
			java.lang.String leaveApplicationStatus) {
		this.leaveApplicationStatus = leaveApplicationStatus;
	}

	public LeaveApplication(int leaveId, java.lang.String leaveType,
			int noOfYearsInCompany, int totNoOfLeaveApplied, int employeeId,
			int leaveBalance, java.lang.String leaveApplicationStatus) {
		this.leaveId = leaveId;
		this.leaveType = leaveType;
		this.noOfYearsInCompany = noOfYearsInCompany;
		this.totNoOfLeaveApplied = totNoOfLeaveApplied;
		this.employeeId = employeeId;
		this.leaveBalance = leaveBalance;
		this.leaveApplicationStatus = leaveApplicationStatus;
	}

}